"""The allowlisted semantic model for analytical sales-call queries.

This is the source of truth for what a model may ask about ``calls``. It is
business-oriented: database column names and sensitive text fields are not part
of the public query language.
"""

from datetime import date
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, model_validator


class CallMetric(StrEnum):
    CALL_COUNT = "call_count"


class CallDimension(StrEnum):
    CALL_DATE = "call_date"
    SALES_ID = "sales_id"
    SALES_STAGE = "sales_stage"
    ANALYSIS_STATUS = "analysis_status"
    CALL_ID = "call_id"


class FilterOperator(StrEnum):
    EQ = "eq"
    IN = "in"
    GTE = "gte"
    LTE = "lte"


class SortDirection(StrEnum):
    ASC = "asc"
    DESC = "desc"


class SemanticModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class CallFilter(SemanticModel):
    field: CallDimension
    operator: FilterOperator
    value: str | list[str]

    @model_validator(mode="after")
    def validate_against_catalog(self) -> "CallFilter":
        if self.field == CallDimension.CALL_ID:
            raise ValueError("call_id cannot be used as a filter")
        if self.field == CallDimension.CALL_DATE:
            if self.operator == FilterOperator.IN:
                raise ValueError("call_date does not support the in operator")
            if not isinstance(self.value, str):
                raise ValueError("call_date requires one YYYY-MM-DD value")
            try:
                date.fromisoformat(self.value)
            except ValueError as exc:
                raise ValueError("call_date must use YYYY-MM-DD") from exc
        elif self.operator == FilterOperator.IN:
            if not isinstance(self.value, list) or not self.value:
                raise ValueError("the in operator requires a non-empty list")
        elif not isinstance(self.value, str):
            raise ValueError("this operator requires one string value")
        return self


class OrderBy(SemanticModel):
    field: CallMetric | CallDimension
    direction: SortDirection = SortDirection.DESC


class QueryCallsInput(SemanticModel):
    """A bounded, declarative query plan generated by the model."""

    metrics: list[CallMetric] = Field(min_length=1, max_length=1, description="当前仅支持 call_count：满足筛选条件的通话记录数。")
    dimensions: list[CallDimension] = Field(default_factory=list, max_length=5, description="可分组字段：call_date（日期）、sales_id（销售员）、sales_stage（销售阶段）、analysis_status（分析状态）、call_id（通话记录）。")
    filters: list[CallFilter] = Field(default_factory=list, max_length=10, description="可筛选日期、销售员、销售阶段和分析状态；不可筛选通话文本或 user_id。")
    order_by: list[OrderBy] = Field(default_factory=list, max_length=3, description="只能按已选择的指标或维度排序。")
    limit: int = Field(default=50, ge=1, le=100)
    offset: int = Field(default=0, ge=0, le=10000, description="分页偏移量；首次查询使用 0，后续使用工具返回的 next_offset。")

    @model_validator(mode="after")
    def validate_query_shape(self) -> "QueryCallsInput":
        if self.metrics != [CallMetric.CALL_COUNT]:
            raise ValueError("call_count is the only currently supported metric")
        if len(set(self.dimensions)) != len(self.dimensions):
            raise ValueError("dimensions must not contain duplicates")
        allowed_order_fields = {CallMetric.CALL_COUNT, *self.dimensions}
        if any(item.field not in allowed_order_fields for item in self.order_by):
            raise ValueError("order_by fields must be a selected metric or dimension")
        return self


CALLS_CATALOG: dict[str, Any] = {
    "name": "sales_calls",
    "description": "当前用户的销售通话统计数据。通话量按 calls 表中的记录计数。",
    "metrics": [
        {"name": CallMetric.CALL_COUNT, "label": "通话量", "definition": "满足筛选条件的 calls 记录数。"}
    ],
    "dimensions": [
        {"name": CallDimension.CALL_DATE, "label": "通话日期", "type": "date", "synonyms": ["哪天", "日期", "每天"]},
        {"name": CallDimension.SALES_ID, "label": "销售员", "type": "string", "synonyms": ["销售", "销售人员", "销售员"]},
        {"name": CallDimension.SALES_STAGE, "label": "销售阶段", "type": "string", "synonyms": ["阶段"]},
        {"name": CallDimension.ANALYSIS_STATUS, "label": "分析状态", "type": "string", "synonyms": ["分析完成情况"]},
        {"name": CallDimension.CALL_ID, "label": "通话记录 ID", "type": "uuid", "synonyms": ["通话记录", "哪几通"]},
    ],
    "filter_operators": {
        "call_date": ["eq", "gte", "lte"],
        "sales_id": ["eq", "in"],
        "sales_stage": ["eq", "in"],
        "analysis_status": ["eq", "in"],
    },
    "excluded_fields": ["raw_source_text", "transcript_text", "source_hash", "user_id"],
    "limits": {"max_dimensions": 5, "max_filters": 10, "max_rows": 100, "max_offset": 10000},
}
